---
apiVersion: v1
kind: Service
metadata:
  name: poet-grpc
  labels:
    app: poet
spec:
  type: NodePort
  selector:
    app: poet
  ports:
    - protocol: TCP
      nodePort: 30081
      port: 50002
      targetPort: 50002

# vim:ts=2 sw=2 et:
