FROM spacemeshos/go-spacemesh

### Run as user root
USER root

### Install AWS CLI
RUN apk update

# Prefer bundled Python libraries
RUN apk add \
    python3 \
    py3-docutils \
    py3-dateutil \
    py3-urllib3 \
    py3-rsa \
    py3-six
RUN pip3 install --upgrade pip
RUN pip3 install awscli~=1.16.0

### Create an unprivileged user (FIXME: Move to main Dockerfile)
RUN adduser -D spacemesh

COPY --chown=root:root wrapper.py /bin/spacemesh-miner-wrapper.py
RUN chmod 0755 /bin/spacemesh-miner-wrapper.py

### Default command
USER spacemesh
WORKDIR /home/spacemesh
ENTRYPOINT ["/bin/sh"]

