aws_region = "us-east-1"
kubectl = "kubectl --context=miner-${aws_region}"

default_miner_image = "spacemeshos/go-spacemesh:787b038"
init_miner_image    = "534354616613.dkr.ecr.us-east-1.amazonaws.com/spacemesh-testnet-miner-init:latest"

/* FIXME: This assumes the time is in GMT */
default_genesis_time = (new Date(currentBuild.startTimeInMillis + 600*1000)).format("yyyy-MM-dd'T'HH:mm:ss'+00:00'")

/* FIXME: Move to ConfigMap */
coin_base = "0x1234"
poet_url  = "spacemesh-testnet-poet-grpc-lb-f34cb9e80d3b5d58.elb.us-east-1.amazonaws.com:50002"

/* Pipeline global vars */
def miner_count
def worker_ports = []
def bootstrap_addr
def bootstrap_pod
def bootstrap_tcp_port
def bootstrap_grpc_port
def bootstrap_id
def bootnodes

/* Library function: call script and return stdout */
def shell(cmd) {
  return sh(returnStdout: true, script: cmd).trim()
}

/* Library function: generate random hex string */
def random_id = {->
  rnd = new Random()

  return {-> String.format("%06x",(rnd.nextFloat() * 2**31) as Integer)[0..5]}
}()

def create_service(svc, pool_id, node, proto, port) {
  echo "Writing service manifest for ${svc}"
  writeFile file: "${svc}-svc.yml", text: """\
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: ${svc}
    labels:
      app: miner
      miner-pool: \"${pool_id}\"
  spec:
    type: NodePort
    selector:
      miner-node: \"${node}\"
    ports:
    - protocol: ${proto.toUpperCase()}
      port: ${port}
  """.stripIndent()

  echo "Creating service ${svc}"
  sh """${kubectl} create -f ${svc}-svc.yml"""
}

def random_ports(int ctr, int low=61000, int high=65535) {
  def rand_port = {->
    def rnd = new Random()
    return {-> (low + (high-low)*rnd.nextFloat()) as int }
  }()

  def ports = []
  (1..ctr).each({
    def r = rand_port()
    while(r in ports)
      r = rand_port()
    ports.add(r)
  })

  return ports
}

def get_bootstrap_pod = {pool_id ->
  """\
  ${kubectl} get pod -l miner-node=miner-${pool_id}-bootstrap --template '{{\$i := index .items 0 }}{{\$i.metadata.name}} {{\$i.status.phase}} {{\$i.spec.nodeName}}' 2>/dev/null
  """.stripIndent().trim()
}

def bootstrap_manifest = {pool_id, miner_image ->
  """\
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: miner-${pool_id}-bootstrap
    labels:
      app: miner
      miner-pool: \"${pool_id}\"
      miner-node: miner-${pool_id}-bootstrap
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: miner-bootstrap
    template:
      metadata:
        labels:
          app: miner-bootstrap
          miner-pool: \"${pool_id}\"
          miner-node: miner-${pool_id}-bootstrap
      spec:
        volumes:
          - name: miner-storage
            emptyDir: {}

        initContainers:
          - name: miner-init
            image: \"${init_miner_image}\"
            env:
              - name: SPACEMESH_S3_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_s3_bucket
              - name: SPACEMESH_S3_PREFIX
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_s3_prefix
              - name: SPACEMESH_DYNAMODB_TABLE
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_dynamodb_table
              - name: SPACEMESH_DYNAMODB_REGION
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_dynamodb_region
              - name: SPACEMESH_WORKER_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: SPACEMESH_WORKDIR
                value: "/root"
              - name: SPACEMESH_DATADIR
                value: "./post/data"

            volumeMounts:
              - name: miner-storage
                mountPath: /root

        containers:
          - name: default
            image: \"${miner_image}\"
            imagePullPolicy: "Always"

            ports:
              - protocol: TCP
                containerPort: ${bootstrap_tcp_port}
                hostPort: ${bootstrap_tcp_port}
              - protocol: UDP
                containerPort: ${bootstrap_tcp_port}
                hostPort: ${bootstrap_tcp_port}

            env:
              - name: SPACEMESH_MINER_PORT
                value: \"${bootstrap_tcp_port}\"
              - name: SPACEMESH_GRPC_PORT
                value: \"${bootstrap_grpc_port}\"
              - name: SPACEMESH_COINBASE
                value: \"${coin_base}\"
              - name: SPACEMESH_POET_GRPC
                value: \"${poet_url}\"
            args: [ "--config", "/root/config.toml",
                    "--grpc-server", "--grpc-port", \$(SPACEMESH_GRPC_PORT),
                    "--tcp-port",    \$(SPACEMESH_MINER_PORT),
                    "--coinbase",    \$(SPACEMESH_COINBASE),
                    "--poet-server", \$(SPACEMESH_POET_GRPC),
                    "--genesis-time", \"${params.GENESIS_TIME}\",
                  ]
            resources:
              limits:
                cpu: 1000m
              requests:
                cpu: 100m
            volumeMounts:
              - name: miner-storage
                mountPath: /root
  """.stripIndent()
}

def worker_manifest = {pool_id, miner_image, worker_id, port ->
  """\
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: miner-${pool_id}-node-${worker_id}
    labels:
      app: miner
      miner-pool: \"${pool_id}\"
      miner-node: miner-${pool_id}-node-${worker_id}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: miner
    template:
      metadata:
        labels:
          app: miner
          miner-pool: \"${pool_id}\"
          miner-node: miner-${pool_id}-node-${worker_id}
      spec:
        volumes:
          - name: miner-storage
            emptyDir: {}

        initContainers:
          - name: miner-init
            image: \"${init_miner_image}\"
            env:
              - name: SPACEMESH_S3_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_s3_bucket
              - name: SPACEMESH_S3_PREFIX
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_s3_prefix
              - name: SPACEMESH_DYNAMODB_TABLE
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_dynamodb_table
              - name: SPACEMESH_DYNAMODB_REGION
                valueFrom:
                  configMapKeyRef:
                    name: spacemesh-testnet-miner
                    key: initdata_dynamodb_region
              - name: SPACEMESH_WORKER_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: SPACEMESH_WORKDIR
                value: "/root"
              - name: SPACEMESH_DATADIR
                value: "./post/data"

            volumeMounts:
              - name: miner-storage
                mountPath: /root

        containers:
          - name: default
            image: \"${miner_image}\"
            imagePullPolicy: "Always"

            ports:
              - protocol: UDP
                containerPort: ${port}
                hostPort: ${port}
              - protocol: TCP
                containerPort: ${port}
                hostPort: ${port}

            env:
              - name: SPACEMESH_MINER_PORT
                value: \"${port}\"
              - name: SPACEMESH_COINBASE
                value: \"${coin_base}\"
              - name: SPACEMESH_POET_GRPC
                value: \"${poet_url}\"
            args: [ "--config", "/root/config.toml",
                    "--tcp-port", \$(SPACEMESH_MINER_PORT),
                    "--coinbase",    \$(SPACEMESH_COINBASE),
                    "--poet-server", \$(SPACEMESH_POET_GRPC),
                    "--genesis-time", \"${params.GENESIS_TIME}\",
                    "--bootstrap", "--bootnodes", \"${bootnodes}\",
                  ]
            resources:
              limits:
                cpu: 1000m
              requests:
                cpu: 100m
            volumeMounts:
              - name: miner-storage
                mountPath: /root
  """.stripIndent()
}

def get_node_inst_id = {node ->
  """\
  ${kubectl} get node ${node} --template '{{.spec.providerID}}' | sed -e 's/.\\+\\///'
  """.stripIndent()
}

def get_instance_ip = {inst_id ->
  """\
  aws ec2 describe-instances --region=${aws_region} --instance-ids ${inst_id} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text
  """.stripIndent()
}

def get_bootstrap_id = {pod ->
  """\
  ${kubectl} logs ${pod} --tail=-1 -f |\\
  sed -ne '/Local node identity / { s/.\\+Local node identity >> \\([a-zA-Z0-9]\\+\\).*/\\1/ ; p; q; }'
  """.stripIndent()
}

/*
  PIPELINE
 */
pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '5')) // Keep last 5 builds only
  }

  parameters {
    string name: 'MINER_COUNT', defaultValue: '', description: 'Number of the miners to start', trim: true
    string name: 'MINER_IMAGE', defaultValue: default_miner_image, description: 'Miner pool id', trim: true
    string name: 'POOL_ID',     defaultValue: '', description: 'Miner pool id', trim: true
    string name: 'GENESIS_TIME', defaultValue: default_genesis_time, description: 'Genesis time', trim: true
  }

  stages {
    stage("Prepare") {
      steps {
        script {
          miner_count = params.MINER_COUNT as int
          assert miner_count > 0
          pool_id = params.POOL_ID ?: random_id()
          worker_ports = random_ports(miner_count + 1)
          bootstrap_tcp_port = worker_ports.pop()
          worker_ports.sort()
        }
        echo "Number of miners: ${miner_count}"
        echo "Miner pool ID: ${pool_id}"
        echo "Bootstrap port: ${bootstrap_tcp_port}"
        echo "Miner ports: ${worker_ports}"
      }
    }

    stage("Create bootstrap gRPC service") {
      steps {
        script {
          def boot_node = "miner-${pool_id}-bootstrap"
          create_service("${boot_node}-grpc", pool_id, boot_node, "TCP", 9091)

          echo "Getting allocated port"
          bootstrap_grpc_port = shell("""\
            ${kubectl} get svc ${boot_node}-grpc --template '{{(index .spec.ports 0).nodePort}}'""")
        }

        echo "Bootstrap GRPC port: ${bootstrap_grpc_port}"
      }
    }

    /* FIXME: Add PVC here */

    stage("Create bootstrap miner") {
      steps {
        echo "Generating manifest"
        writeFile file: "bootstrap-${pool_id}-deploy.yml", text: bootstrap_manifest(pool_id, params.MINER_IMAGE)
        echo "Creating bootstrap Deployment"
        sh """${kubectl} create -f bootstrap-${pool_id}-deploy.yml"""
        echo "Waiting for the bootstrap pod to be scheduled..."
        script {
          def pod_node

          /* Wait until a pod in a Running state appears */
          timeout(time: 600, unit: 'SECONDS') {
            waitUntil {
              try {
                (bootstrap_pod, pod_status, pod_node) = shell(get_bootstrap_pod(pool_id, miner_image)).split()
                pod_status == "Running"
              } catch(all) {
                false
              }
            }
          }

          echo "Running on node ${pod_node}, getting AWS instance id"
          def inst_id = shell(get_node_inst_id(pod_node))

          echo "Getting AWS instance '${inst_id}' public IP"
          bootstrap_addr = shell(get_instance_ip(inst_id))
        }
        echo "Bootstrapping from: ${bootstrap_addr}:${bootstrap_tcp_port}"

        echo "Getting bootstrap miner_id from the logs"
        script {
          timeout(time: 600, unit: 'SECONDS') {
            bootstrap_id = shell(get_bootstrap_id(bootstrap_pod))
          }
        }
        echo "Bootstrap ID: ${bootstrap_id}"

        script {
          bootnodes = "spacemesh://${bootstrap_id}@${bootstrap_addr}:${bootstrap_tcp_port}"
        }

        echo """\
          >>> Bootstrap nodes: ${bootnodes}
          >>> PoET --nodeaddr: ${bootstrap_addr}:${bootstrap_grpc_port}
          """.stripIndent()
      }
    }

    stage("Create workers") {
      steps {
        script {
          worker_ports.eachWithIndex({port, i ->
            i++
            echo "Generating manifest for worker #${i}"
            writeFile file: "miner-${pool_id}-node-${i}-deploy.yml", \
                      text: worker_manifest(pool_id, params.MINER_IMAGE, i, port)
            echo "Creating Deployment for worker #${i}"
            sh """${kubectl} create -f miner-${pool_id}-node-${i}-deploy.yml"""
          })
        }
      }
    }

    stage("Archive artifacts") {
      steps {
        archiveArtifacts "*-${pool_id}-*.yml"
      }
    }
  }
}

/* vim: set filetype=groovy ts=2 sw=2 et : */
