---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initfactory
data:
  initdata_dynamodb_region: ap-northeast-2
  initdata_dynamodb_table: testnet-initdata.ap-northeast-2.spacemesh.io
  initdata_s3_bucket: testnet-initdata.ap-northeast-2.spacemesh.io
  initdata_s3_prefix: ""
  poet_url: spacemesh-testnet-poet-grpc-lb-8f4a4fc1729801b2.elb.ap-northeast-2.amazonaws.com:50002
  poet_nodeaddr: ""
  spacemesh_coinbase: "0x1234"
