---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-xxx
  labels:
    app: miner
    name: miner-xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner
  template:
    metadata:
      labels:
        app: miner
    spec:
      volumes:
        - name: miner-storage
          persistentVolumeClaim:
            claimName: miner-pv-claim

      containers:
        - name: default
          image: "spacemeshos/go-spacemesh:787b038"
          imagePullPolicy: "Always"
          env:
            - name: SPACEMESH_MINER_PORT
              value: "9091"
            - name: SPACEMESH_COINBASE
              value: "0x1234"
            - name: SPACEMESH_POET_GRPC
              value: "spacemesh-testnet-poet-grpc-lb-f34cb9e80d3b5d58.elb.us-east-1.amazonaws.com:50002"
          args: [ "--grpc-server", "--grpc-port", "$(SPACEMESH_MINER_PORT)",
                  "--coinbase",    "$(SPACEMESH_COINBASE)",
                  "--poet-server", "$(SPACEMESH_POET_GRPC)",
                ]

          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m

          volumeMounts:
            - mountPath: /root
              name: miner-storage
