---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-nginx
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: rest
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: grpc
  selector:
    app: miner
---
apiVersion: v1
kind: Service
metadata:
  name: api-nginx
  labels:
    app: api-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: rest
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: grpc
  selector:
    app: api-nginx
---
apiVersion: v1
data:
  default.conf: |-
    upstream api {
      server api-service:9090;
      server api-service:9091;
    }
        
    server {
      listen 9090;
      listen 9091 http2;
      
      # Mesh
      location /v1/stateroot {
        proxy_pass http://api/v1/stateroot;
      }
      location /v1/genesis {
        proxy_pass http://api/v1/genesis;
      }
      location /v1/nodestatus {
        proxy_pass http://api/v1/nodestatus;
      }

      # Accounts
      location /v1/nonce {
        proxy_pass http://api/v1/nonce;
      }
      location /v1/accountrewards {
        proxy_pass http://api/v1/accountrewards;
      }
      location /v1/balance {
        proxy_pass http://api/v1/balance;
      }

      # Transactions
      location /v1/accounttxs {
        proxy_pass http://api/v1/accounttxs;
      }
      location /v1/gettransaction {
        proxy_pass http://api/v1/gettransaction;
      }
      location /v1/submittransaction {
        proxy_pass http://api/v1/submittransaction;
      }
    }
kind: ConfigMap
metadata:
  name: api-nginx-files
  labels:
    app: api-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nginx
  labels:
    app: api-nginx
spec:
  selector:
    matchLabels:
      app: api-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: api-nginx
    spec:
      nodeSelector:
        pool: miner
      tolerations:
      - key: dedicated
        operator: Equal
        value: miner
        effect: NoSchedule
      volumes:
      - name: config-map
        configMap:
          name: api-nginx-files
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 9090
        - containerPort: 9091
        volumeMounts:
        - name: config-map
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf