---
apiVersion: v1
kind: Service
metadata:
  name: config-toml
  labels:
    app: config-toml
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: config-toml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-toml
  labels:
    app: config-toml
spec:
  selector:
    matchLabels:
      app: config-toml
  replicas: 1
  template:
    metadata:
      labels:
        app: config-toml
    spec:
      nodeSelector:
        pool: miner
      tolerations:
        - key: dedicated
          operator: Equal
          value: miner
          effect: NoSchedule
      volumes:
      - name: config-map
        configMap:
          name: miner-files
      containers:
      - name: miniserve
        image: svenstaro/miniserve:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-map
          mountPath: /root/config/config.toml
          subPath: config.toml
        args:
        - /root/config/config.toml